name: Linter

on:
  pull_request:
    paths:
    - ansible/**
    branches:         
    - master
  push:
    paths:
    - ansible/**
    branches:         
    - master


jobs:
  yamlint:
    name: Yamlint
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yamllint==1.13.0

    - name: yamlint
      run: |
        cd ansible
        yamllint -c yamllint.yml .

  ansible_lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 2.x
      uses: actions/setup-python@v2
      with:
        python-version: '2.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible ansible-lint==4.2.0

    - name: ansible_lint
      run: | 
        cd ansible
        # Check that the inventory is valid
        ansible-inventory --host build-marist-rhel77-s390x-1

        # Ansible code static analysis
        ansible-lint -x 403,204 playbooks/AdoptOpenJDK_Unix_Playbook/main.yml
        ansible-lint -x 403,204 playbooks/AdoptOpenJDK_Windows_Playbook/main.yml
        ansible-lint -x 403,204 playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-jckservices.yml
        ansible-lint -x 403,204 playbooks/AdoptOpenJDK_ITW_Playbook/main.yml
        ansible-lint -x 403,204 playbooks/aix.yml
        ansible-lint -x 403,204 playbooks/vagrant.yml
        ansible-lint -x 403,204 playbooks/ubuntu-jck.yml

        # Check Playbook syntax.
        ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Unix_Playbook/trss.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Windows_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_Services_Playbooks/ubuntu-jckservices.yml --syntax-check
        ansible-playbook playbooks/AdoptOpenJDK_ITW_Playbook/main.yml --syntax-check
        ansible-playbook playbooks/vagrant.yml --syntax-check
        ansible-playbook playbooks/aix.yml --syntax-check
        ansible-playbook playbooks/ubuntu-jck.yml --syntax-check